[project]
name = "tfc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.3.0",
    "pytest>=8.4.2",
    "seaborn>=0.13.2",
    "torch>=2.9.0",
    "wandb>=0.22.3",
]
